<?php

namespace Tests\Unit;

use App\Models\Category;
use App\Models\Traits\Uuid;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

#Classe especifica - vendor/bin/phpunit tests/unit/CategoryTest.php
#Metodo especifico em um arquivo - vendor/bin/phpunit --filter testIfUseTraits tests/unit/CategoryTest.php
#Metodo especifico em uma classe - vendor/bin/phpunit --filter CategoryTest::testIfUseTratis


class CategoryTest extends TestCase
{
    use DatabaseMigrations;

    private $category;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp();
        $this->category = new Category();
    }

    protected function tearDown(): void
    {
        parent::tearDown();

    }

    public static function tearDownAfterClass(): void
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }

    public function testFillableAttribute()
    {
        Category::create(['name' => 'test']);
        $fillable = ['name','description','is_active'];
        $this->assertEquals($fillable, $this->category->getFillable());
    }

    public function testIfUseTraitAttribute()
    {
        $traits = [
            SoftDeletes::class, Uuid::class
        ];
        $categoryTraits = array_keys(class_uses(Category::class));
        $this->assertEquals($traits, $categoryTraits);
    }

    public function testCatsAttribute()
    {
        $casts = ['id' => 'string', 'is_active' => 'bool'];
        $this->assertEquals($casts, $this->category->getCasts());
    }

    public function testIncreMenting()
    {
        $this->assertFalse($this->category->incrementing);
    }

    public function testDatesAttribute()
    {
        $dates = ['deleted_at', 'created_at', 'updated_at'];
        foreach ($dates as $date) {
            $this->assertContains($date, $this->category->getDates());
        }
        $this->assertCount(count($dates), $this->category->getDates());
    }
}
